### PR TITLE
Fixed editor changes in 3.5

### LINKED ISSUE #72: Scatter is not working with Godot 3.5
Godot has recently released version 3.5 beta 3 and unfortunatly it seems to break Scatter.

When enabling Scatter in the plugins tab, I get:

```
 res://addons/scatter/plugin.gd:141 - Invalid call. Nonexistent function 'add_child' in base 'Nil'.
 res://addons/scatter/src/tools/path_gizmo/gizmo_options.gd:56 - Invalid get index 'color' (on base: 'Nil').
 res://addons/scatter/src/tools/path_gizmo/scatter_path_gizmo_plugin.gd:380 - Invalid type in function 'create_custom_material' in base 'EditorSpatialGizmoPlugin (scatter_path_gizmo_plugin.gd)'. Cannot convert argument 2 from Nil to Color.
```

and when switching to showcase.tscn:

```
 Script inherits from native type 'Reference', so it can't be instanced in object of type 'Node'.
 Script inherits from native type 'Reference', so it can't be instanced in object of type 'Node'.
 res://addons/scatter/src/tools/path_gizmo/gizmo_options.gd:66 - Invalid set index 'pressed' (on base: 'Nil') with value of type 'bool'.
 res://addons/scatter/src/modifiers/exclude_along_path.gd:48 - Invalid get index 'Util' (on base: 'Node').
 res://addons/scatter/src/modifiers/exclude_along_path.gd:48 - Invalid get index 'Util' (on base: 'Node').
 res://addons/scatter/src/modifiers/exclude_around_point.gd:62 - Invalid get index 'Point' (on base: 'Node').
 res://addons/scatter/src/modifiers/exclude_around_point.gd:72 - Invalid call. Nonexistent function 'size' in base 'Nil'.
 res://addons/scatter/src/modifiers/exclude_around_point.gd:39 - Invalid get index 'Util' (on base: 'Node').
 res://addons/scatter/src/tools/path_gizmo/gizmo_options.gd:66 - Invalid set index 'pressed' (on base: 'Nil') with value of type 'bool'.
```

### PR DESCRIPTION
**Pull request by addmix**
Fixes #72

### CODE REVIEW

**Comment by HungryProton** [comment]
Thanks for the PR!
I'm testing it currently but it doesn't seem to fix the issue. Might be an issue on my side, I'll keep testing.

**Comment by addmix** [comment]
I traced the issue to changes in the layout of the editor. Maybe I should have left my path debugging code in.

**Comment by addmix** [comment]
I've changed how the SpatialEditorViewport is navigated to, it's a good bit slower than what was previously there, but it should withstand most editor changes, up until someone adds a second SpatialEditorViewport node somewhere. Compatibility should now be maintained for previous versions.

**Comment by HungryProton** [comment]
Looks good to me, thanks for the fix!

**Pull request merged**
