### PR TITLE
Compute shader relax

### PR DESCRIPTION
**Pull request by Norodix**
Created a compute shader that significantly speeds up the otherwise slow relax modifier.

The compute shader performs almost the same calculations except on the GPU.
There is a small difference, the script updates the positions of the nodes one by one and the shader computes it in one go. The difference in most cases is insignificant. 

The shader can be turned off and the old implementation can be used in case the target device does not support compute shaders under godot.

The speed difference is huge. It took about 25 seconds on my machine to relax 10k points. Using the compute shader implementation it takes about 25 ms.

### CODE REVIEW

**Comment by HungryProton** [comment]
Thanks a lot for the PR! I can notice the drastic performance improvement, even with a small amount of transforms.

I'm testing on 4.1 for now (haven't tried on 4.0 yet), do you also have this kind of errors too?
```
 drivers/vulkan/rendering_device_vulkan.cpp:8403 - Attempted to free invalid ID: 0 
  drivers/vulkan/rendering_device_vulkan.cpp:8403 - Attempted to free invalid ID: 0 
  drivers/vulkan/rendering_device_vulkan.cpp:8403 - Attempted to free invalid ID: 0 
  drivers/vulkan/rendering_device_vulkan.cpp:8403 - Attempted to free invalid ID: 1409526662168576 
  drivers/vulkan/rendering_device_vulkan.cpp:9107 - 1 RID of type "Shader" was leaked.
 - RID:1409500892364800
 ```

**Comment by Norodix** [comment]
No, I have not seen this type of error. 
There is a free section at the bottom of the compute relax function, I have seen similar things when trying to free memory. Before that I had a huge memory leak but this version that I uploaded never gave me this error.
Maybe v4 vs v4.1 causes it.

**Comment by Norodix** [comment]
I tested with 4.1 and I get the same errors with it.
Documentation is very sparse regarding compute shaders but under RenderingDevice it says that free_rid should be used.
https://github.com/godotengine/godot-demo-projects/blob/master/misc/compute_shader_heightmap/main.gd
The heightmap example linked to by the documentation also frees objects in a similar manner. 

I assume this is an engine bug.

**Comment by HungryProton** [comment]
Alright, let's merge this and open an issue upstream them.

**Comment by HungryProton** [comment]
That issue should be fixed now. Turns out, the order to free RIDs matters in 4.1, freeing the shader before the pipeline will cause a bug, but not the other way around. Same for the uniform set that needs to be freed before the uniform in and out. No idea if this is a regression or by design, though.

**Comment by Norodix** [comment]
Interesting, I didn't think it would matter. Especially since it didn't in v4. Anyway, I'm happy its fixed.

**Pull request merged**
