### PR TITLE
Split multimesh

### PR DESCRIPTION
**Pull request by Norodix**
I started porting the split multimesh functionality to version 4.

There is still some things to do, but it is in an okay working state.

I think it should not be merged yet, but this would be a good place to discuss design decisions regarding this feature.

### CODE REVIEW

**Comment by Norodix** [comment]
Something silly also happened.
It took about 100ms to create a single multimesh instance. Which was just way too long.
So I started looking into why it happened. The most unexpected line: set_name took about 99ms of the 100.
I messed around a bit and it turns out if I move the set_name line before the add_child it takes basically no time at all.

So I changed it in the single multimesh generation too and the addon overall became much more responsive. This is 100ms on the main thread after calculating transforms that froze the editor for 100ms for each scatter that used instancing.

Its an extremely stupid bug because it should not be a bug, but hey, the addon is faster now!

**Comment by HungryProton** [comment]
Thanks a lot for the PR!

set_name being this slow is, unexpected indeed!

I still need to test it locally, but it looks good to me. I would only change one thing though, instead of adding a new render_mode, make it a separate boolean called `use_chunks` (or another name).
This way I can also do the change to the particle systems in a later update (without having 5 render modes when in reality it's not really a different mode). 

This property may even be enabled by default, I think. If advanced users need to turn it off, they will know where to look.

**Comment by Norodix** [comment]
Changing to a boolean is not a big deal, but it didn't seem to me it would be easy to modify `_update_multimeshes` so I made a separate function.

Maybe instancing could be superceded by it by just using a single chunk, but I did not want to drastically change existing code. I will change it to a boolean for now, we will see how things work out.

One more design question. Now that there is visibility distance built in we should expose that somehow. But I don't know if it would be better per item, per scatter, or copying from the mesh instance. If we copy from the mesh instance then there could be different settings for the merged meshes. We could just ignore them and use the first one found. I don't know which one is better.

**Comment by HungryProton** [comment]
You can keep it as a separate function for now. Just change it in the match statement, under the use_instancing case, add an extra check to either call _update_multimesh or the new _update function.

For the visibility distance, I guess it should be per scatter item, in case some of them are much larger and need to be seen from a longer distance.

**Comment by Norodix** [comment]
True, that makes sense. But is it better to expose this in the scatter item or to copy from the mesh? The effect should be similar. Is there a case where it makes a difference?

**Comment by HungryProton** [comment]
It would only make a difference if you have multiple meshes merged into one. I don't think it's worth it to try to detect this from the source mesh, (unless there's only one).

**Comment by HungryProton** [comment]
Is there anything else you would like to add to this PR? Or should we just merge it as is and fix eventual edge cases later?

**Comment by Norodix** [comment]
I am working on the visibility range thing. After that we can merge.

There is an engine issue I found. I have a workaround but I created an issue on godot's github too.

**Comment by Norodix** [comment]
I think this is reasonably complete. 
I have not performed thorough testing, so it should be tested much more.

I came across a memory leak somewhere, but I think that was due to a messed up state during editing the addon. I cannot reproduce the issue now.

**Comment by HungryProton** [comment]
Just tried it on my end, seems to be working great!

`splits_dimensions` however, is more of a subdivision count than an actual chunk dimension.

Both are fine, but from a UX point of view, I wonder if it makes more sense to expose the chunk size. This way the user don't have to manually update that value everytime they move a shape around.

**Comment by HungryProton** [comment]
I tried to make these changes, the split dimensions end up being an approximation of the actual chunk size, but I don't think it matters.
I've also put the split_dimensions into the Performance group (maybe should be renamed chunk_dimensions to match the boolean name) so if you want I can merge the PR and apply these changes on top

**Comment by Norodix** [comment]
Oh yeah, that makes sense. I didn't think of the dimensions being actual units.

Did you manage to make add the dimensions in a dynamic way? Like now it disappeared when it was not applicable, which is nice. But I don't know of a way to specify the group if I add it in get_properties.

**Comment by HungryProton** [comment]
Yes I made the changes for that. 
You can put the property groups in the property name directly (like `"Performance/Split/split_dimensions"` for example), but then you also have to override the `set(property, value)` and `get(property)` methods otherwise it can't find the actual property.

I'll merge the PR and push my changes

**Comment by Norodix** [comment]
Awesome, didn't know that.
After you applied your changes do you want me to go over the code and rename everyting to "chunk" instead of "split"? 
I dont even remember why I called it split multimesh in the first place, it would be nicer to have a unified name.

**Comment by HungryProton** [comment]
I think that name comes from the Godot 3 version, where the only thing it could do was to split the multimesh into smaller chunks.
But now we also have particles, so chunk is fine. If you feel some of the internal variables should be renamed, go for it, but I think it's fine.

**Pull request merged**
